version: "3"
services:
  koa-server:
    # build: './koa/'
    image: pm2koa # 
    build:
      dockerfile: Dockerfile
      context: ./koa/
    container_name: pm2koa # 指定容器的名称
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - web
      - mysql-db
  web:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf/:/etc/nginx/conf.d/
      - ./web-dist/:/app/
  mysql-db:
    container_name: mysql-db # 指定容器的名称
    image: mysql # 指定镜像和版本
    command:
      --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: table1
    volumes:
      - "./conf/my.cnf:/etc/my.cnf"
      - "./conf/init.sql:/docker-entrypoint-initdb.d/init.sql"